database:
  username: root
  password: 123456
  dbName: giligili
  dbHost: localhost
  dbPort: 3306

HttpPort: :8081

AppMode: debug

SessionSecret: setOnProduction

redis:
  addr: 127.0.0.1:6379
  pwd:
  db: 0